name: Publish docker image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'
  push:
    branches:
      - master

env:
    USERNAME: alekna
    REPO: openbox-desktop-vnc

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag image

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u $USERNAME --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=$USERNAME/$REPO
          VERSION=latest

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
